[package]
name = "ex2-ownership-borrowing"
version = "0.1.0"
authors = ["OliverKain"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
